<h2 id="understanding_data">Here are what the columns represent:</h2>
Loan_ID               object

Gender                object

Married               object

Dependents            object

Education             object

Self_Employed         object

ApplicantIncome        int64

CoapplicantIncome    float64

LoanAmount           float64

Loan_Amount_Term     float64

Credit_History       float64

Property_Area         object

Loan_Status           object

In [2]:
import pandas as pd
import numpy as np
df=pd.read_csv("BankLoanRepayment.csv")
print("DataFrame  shape : ",df.shape)

DataFrame  shape :  (614, 13)


In [3]:
#To -do : 1) GetDummies 2) LabelEncoder

In [4]:
Categorical_Columns=df.select_dtypes(include='object').columns.tolist()
Categorical_Columns.remove('Loan_ID')
print(Categorical_Columns)
Numeric_Columns=df.select_dtypes(exclude='object').columns.tolist()
print(Numeric_Columns)

['Gender', 'Married', 'Dependents', 'Education', 'Self_Employed', 'Property_Area', 'Loan_Status']
['ApplicantIncome', 'CoapplicantIncome', 'LoanAmount', 'Loan_Amount_Term', 'Credit_History']


In [5]:
for n in Categorical_Columns:
    df[n].replace(np.NaN,'NA',inplace=True)
for n in Numeric_Columns:
    df[n].replace(np.NaN,0,inplace=True)

In [6]:
"""df[Categorical_Columns].replace(np.NaN,0,inplace=True)
df['CoapplicantIncome'].replace(np.NaN,0,inplace=True)
df['LoanAmount'].replace(np.NaN,0,inplace=True)
df['Loan_Amount_Term'].replace(np.NaN,0,inplace=True)
df['Credit_History'].replace(np.NaN,0,inplace=True)
df['Gender'].replace(np.NaN,'Undefined',inplace=True)
df['Married'].replace(np.NaN,'Undefined',inplace=True)
df['Dependents'].replace(np.NaN,'0',inplace=True)
df['Education'].replace(np.NaN,'Not Specified',inplace=True)
df['Self_Employed'].replace(np.NaN,'NA',inplace=True)"""

"df[Categorical_Columns].replace(np.NaN,0,inplace=True)\ndf['CoapplicantIncome'].replace(np.NaN,0,inplace=True)\ndf['LoanAmount'].replace(np.NaN,0,inplace=True)\ndf['Loan_Amount_Term'].replace(np.NaN,0,inplace=True)\ndf['Credit_History'].replace(np.NaN,0,inplace=True)\ndf['Gender'].replace(np.NaN,'Undefined',inplace=True)\ndf['Married'].replace(np.NaN,'Undefined',inplace=True)\ndf['Dependents'].replace(np.NaN,'0',inplace=True)\ndf['Education'].replace(np.NaN,'Not Specified',inplace=True)\ndf['Self_Employed'].replace(np.NaN,'NA',inplace=True)"

In [7]:
X=df[['Gender','Married','Dependents','Education','Self_Employed','ApplicantIncome','CoapplicantIncome','LoanAmount',
      'Loan_Amount_Term','Credit_History','Property_Area']].values
y=df[['Loan_Status']].values

In [8]:
from sklearn import preprocessing
import numpy as np

Gender_Unique=np.unique(X[:,0]).tolist()
if('NA' in Gender_Unique):
    Gender_Unique.remove('NA')
    Gender_Unique.insert(0,'NA')
Married_Unique=np.unique(X[:,1]).tolist()
if('NA' in Married_Unique):
    Married_Unique.remove('NA')
    Married_Unique.insert(0,'NA')
Dependents_Unique=np.unique(X[:,2]).tolist()
if('NA' in Dependents_Unique):
    Dependents_Unique.remove('NA')
    Dependents_Unique.insert(0,'NA')
Education_Unique=np.unique(X[:,3]).tolist()
Self_Employed_Unique=np.unique(X[:,4]).tolist()
if('NA' in Self_Employed_Unique):
    Self_Employed_Unique.remove('NA')
    Self_Employed_Unique.insert(0,'NA')
Property_Area_Unique=np.unique(X[:,10]).tolist()
if('NA' in Property_Area_Unique):
    Property_Area_Unique.remove('NA')
    Property_Area_Unique.insert(0,'NA')

In [9]:
#Pre-Processing
from sklearn import preprocessing
import numpy as np
Encoder=preprocessing.LabelEncoder()
X[:,0]=Encoder.fit(Gender_Unique).transform(X[:,0])
X[:,1]=Encoder.fit(Married_Unique).transform(X[:,1])
X[:,2]=Encoder.fit(Dependents_Unique).transform(X[:,2])
X[:,3]=Encoder.fit(Education_Unique).transform(X[:,3])
X[:,4]=Encoder.fit(Self_Employed_Unique).transform(X[:,4])
X[:,10]=Encoder.fit(Property_Area_Unique).transform(X[:,10])

"""X[:,1]=preprocessing.LabelEncoder().fit(Married_Unique).transform(X[:,1])
X[:,3]=preprocessing.LabelEncoder().fit(Dependents_Unique).transform(X[:,3])
X[:,4]=preprocessing.LabelEncoder().fit(Education_Unique).transform(X[:,4])
X[:,10]=preprocessing.LabelEncoder().fit(Property_Area_Unique).transform(X[:,10])"""
"""
Married=preprocessing.LabelEncoder().fit(np.unique(np.array(X[:,1]).delete('Undefined').append('Undefined')))
X[:,1]=Married.transform(X[:,1])

Education=preprocessing.LabelEncoder().fit(np.unique(np.array(X[:,3]).delete('Not Specified').append('Not Specified')))
X[:,3]=Education.transform(X[:,3])

Self_Employed=preprocessing.LabelEncoder().fit(np.unique(np.array(X[:,4]).delete('NA').append('NA')))
X[:,4]=Self_Employed.transform(X[:,4])

Property_Area=preprocessing.LabelEncoder().fit(np.unique(np.array(X[:,10]).delete('Undefined').append('Undefined')))
X[:,10]=Property_Area.transform(X[:,10])"""

"\nMarried=preprocessing.LabelEncoder().fit(np.unique(np.array(X[:,1]).delete('Undefined').append('Undefined')))\nX[:,1]=Married.transform(X[:,1])\n\nEducation=preprocessing.LabelEncoder().fit(np.unique(np.array(X[:,3]).delete('Not Specified').append('Not Specified')))\nX[:,3]=Education.transform(X[:,3])\n\nSelf_Employed=preprocessing.LabelEncoder().fit(np.unique(np.array(X[:,4]).delete('NA').append('NA')))\nX[:,4]=Self_Employed.transform(X[:,4])\n\nProperty_Area=preprocessing.LabelEncoder().fit(np.unique(np.array(X[:,10]).delete('Undefined').append('Undefined')))\nX[:,10]=Property_Area.transform(X[:,10])"

In [10]:
"""X=df[['int.rate','installment','dti']].values
y=df[['not.fully.paid']].values"""

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=4)
#print('X_train :',X_train[0:5])
#print('y_train :',y_train[0:5])


from sklearn.neighbors import KNeighborsClassifier
k = 1
#Train Model and Predict  
neigh = KNeighborsClassifier(n_neighbors = k).fit(X_train,y_train)
neigh
yhat = neigh.predict(X_test)
print(X_test[0:5])
print(y_test[0:5])
print(yhat[0:5])

[[1 1 0 0 1 2526 1783.0 145.0 360.0 1.0 0]
 [1 2 1 0 1 3315 0.0 96.0 360.0 1.0 1]
 [0 2 0 0 1 4583 0.0 112.0 360.0 1.0 0]
 [1 1 0 0 1 3418 0.0 127.0 360.0 1.0 1]
 [1 2 1 0 1 9538 0.0 187.0 360.0 1.0 2]]
[['Y']
 ['Y']
 ['N']
 ['N']
 ['Y']]
['Y' 'Y' 'N' 'N' 'Y']


/srv/conda/envs/notebook/lib/python3.7/site-packages/ipykernel_launcher.py:13: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  del sys.path[0]
/srv/conda/envs/notebook/lib/python3.7/site-packages/sklearn/neighbors/base.py:908: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  self._y = np.empty(y.shape, dtype=np.int)


In [11]:
from sklearn import metrics
print("Train set Accuracy: ", metrics.accuracy_score(y_train, neigh.predict(X_train)))
print("Test set Accuracy: ", metrics.accuracy_score(y_test, yhat),'\n')

from sklearn.metrics import jaccard_score
print('Train Jaccard Score is : ',jaccard_score(y_train,neigh.predict(X_train),pos_label='Y'))
print('Test Jaccard Score is : ',jaccard_score(y_test,yhat,pos_label='Y'),'\n')

from sklearn.metrics import f1_score
print('Train F1_Score Score is : ',f1_score(y_train,neigh.predict(X_train),pos_label='Y'))
print('Test F1_Score Score is : ',f1_score(y_test,yhat,pos_label='Y'),'\n')

from sklearn.metrics import log_loss
print('Train Log_loss Score is : ',log_loss(list(map(lambda x:int(str(x).replace("['Y']",'1').replace("['N']",'0')), y_train.tolist())),
                    list(map(lambda x:int(x.replace('Y','1').replace('N','0')), neigh.predict(X_train).tolist()))))
print('Test Log_loss Score is : ',log_loss(list(map(lambda x:int(str(x).replace("['Y']",'1').replace("['N']",'0')), y_test.tolist())),list(map(lambda x:int(x.replace('Y','1').replace('N','0')), yhat.tolist()))))

Train set Accuracy:  1.0
Test set Accuracy:  0.5853658536585366 

Train Jaccard Score is :  1.0
Test Jaccard Score is :  0.5363636363636364 

Train F1_Score Score is :  1.0
Test F1_Score Score is :  0.6982248520710059 

Train Log_loss Score is :  9.992007221626413e-16
Test Log_loss Score is :  14.321131587569594


In [36]:
from sklearn.tree import DecisionTreeClassifier
drugTree = DecisionTreeClassifier(criterion="entropy", max_depth = 10)
drugTree # it shows the default parameters
drugTree.fit(X_train,y_train)
predTree = drugTree.predict(X_test)
print(predTree [0:5])
print(list(map(lambda x:str(x).replace('[','').replace(']',''),y_test[0:5].tolist())))

['Y' 'Y' 'Y' 'Y' 'Y']
["'Y'", "'Y'", "'N'", "'N'", "'Y'"]


/srv/conda/envs/notebook/lib/python3.7/site-packages/sklearn/tree/tree.py:163: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  y_encoded = np.zeros(y.shape, dtype=np.int)


In [37]:
from sklearn import metrics
print("Train set Accuracy: ", metrics.accuracy_score(y_train, neigh.predict(X_train)))
print("Test set Accuracy: ", metrics.accuracy_score(y_test, predTree),'\n')

from sklearn.metrics import jaccard_score
print('Train Jaccard Score is : ',jaccard_score(y_train,neigh.predict(X_train),pos_label='Y'))
print('Test Jaccard Score is : ',jaccard_score(y_test,predTree,pos_label='Y'),'\n')

from sklearn.metrics import f1_score
print('Train F1_Score Score is : ',f1_score(y_train,neigh.predict(X_train),pos_label='Y'))
print('Test F1_Score Score is : ',f1_score(y_test,predTree,pos_label='Y'),'\n')

from sklearn.metrics import log_loss
print('Train Log_loss Score is : ',log_loss(list(map(lambda x:int(str(x).replace("['Y']",'1').replace("['N']",'0')), y_train.tolist())),
                    list(map(lambda x:int(x.replace('Y','1').replace('N','0')), neigh.predict(X_train).tolist()))))
print('Test Log_loss Score is : ',log_loss(list(map(lambda x:int(str(x).replace("['Y']",'1').replace("['N']",'0')), y_test.tolist())),list(map(lambda x:int(x.replace('Y','1').replace('N','0')), predTree.tolist()))))

Train set Accuracy:  1.0
Test set Accuracy:  0.6504065040650406 

Train Jaccard Score is :  1.0
Test Jaccard Score is :  0.6018518518518519 

Train F1_Score Score is :  1.0
Test F1_Score Score is :  0.7514450867052022 

Train Log_loss Score is :  9.992007221626413e-16
Test Log_loss Score is :  12.074694105015563
